//! AutoGram Rust core — Grammers-only MTProto backend (no Python Telethon runtime).

pub use autogram_core;
pub mod adaptive_rate_governor;
pub mod capability;
pub mod channel_sync_manager;
pub mod channel_sync_types;
pub mod channel_sync_worker;
pub mod config_normalize;
pub mod forwarder_contract;
pub mod forwarder_engine;
pub mod forwarder_scheduler;
pub mod doc_preview;
pub mod drive_engine;
pub mod drive_rpc;
pub mod grammers;
pub mod hardware_capability;
pub mod media_index_bench;
pub use grammers as grammers_media;
pub mod app_db;
pub mod automations_db;
pub mod download_registry;
pub mod dup_checker;
pub mod events;
pub mod fingerprint;
pub mod grammers_ops;
pub mod grammers_sparse_zip;
pub mod hash_util;
pub mod job_queue;
pub use job_queue as migration_queue;
pub mod jobs_db;
pub use jobs_db as migration_tasks_db;
pub mod media_bench;
pub use media_bench as network_latency_probe;
pub mod media_classifier;
pub mod media_counter;
pub mod media_index_types;
pub mod media_index_worker;
pub mod media_meta;
pub mod media_mutation;
pub mod media_prep;
pub mod media_statistics;
pub mod memory_gc;
pub mod migration_run;
pub mod moov_sidecar;
pub mod mp4_keyframe;
pub mod network;
pub mod path_policy;
pub mod preview_diagnostics;
pub mod preview_transcoder;
pub mod profiles_db;
pub mod progress_rate;
pub mod remote_link_resolver;
pub mod session_guard;
pub mod session_rate;
pub mod session_update_router;
pub mod smart_scanner;
pub mod smart_throttle;
pub mod stats_db;
pub mod stream_server;
pub mod streaming_policy;
pub mod traffic_governor;
pub mod studio_orch;
pub use studio_orch as drive_upload_orchestrator;
pub mod telegram_ops;
pub mod telegram_rpc_guard;
pub mod telethon_session_import;
pub mod tg_error;
pub mod tg_log;
pub mod transfer_journal;
pub mod transfer_state;
pub mod remote_transfer;
pub mod zip_local;
pub mod ytdlp_plugin;
