/**
 * Smart Link Resolver Core Types
 * Defines interfaces for modular platform resolvers, stream formats, and extracted media metadata.
 */

export type PlatformKind =
  | 'youtube'
  | 'tiktok'
  | 'gdrive'
  | 'dropbox'
  | 'mediafire'
  | 'terabox'
  | 'pikpak'
  | 'pinterest'
  | 'pixiv'
  | 'instagram'
  | 'facebook'
  | 'twitter'
  | 'direct';

export type QualityTier = '8k' | '4k' | '2k' | '1080p' | '720p' | '480p' | '360p' | '240p' | '144p' | 'audio' | 'subtitle' | 'original';

export interface RawStreamItem {
  itag: number;
  qualityLabel?: string;
  mimeType: string;
  codec: string;
  bitrate: number;
  bitrateFormatted: string;
  fps?: number;
  filesizeBytes?: number;
  type: 'video' | 'audio' | 'muxed';
  directUrl: string;
  isHdr?: boolean;
  /** Transport that produced the stream (DASH HTTPS, HLS, etc.). */
  protocol?: string;
  /** Container reported by the provider, when available. */
  container?: string;
  width?: number;
  height?: number;
  sampleRate?: number;
  audioChannels?: number;
  /** False when a provider only returned a metadata placeholder. */
  isDownloadable?: boolean;
  isStreamable?: boolean;
  /** The source can be fetched by the extractor but is not browser-playable. */
  downloadOnly?: boolean;
}

export interface SubtitleTrackItem {
  id: string;
  languageCode: string;
  languageName: string;
  isAutoGenerated: boolean;
  directUrl: string;
  vssId?: string;
}

export interface StreamQualityFormat {
  id: string;
  label: string;
  qualityTier: QualityTier;
  resolution?: string; // e.g. "4320p", "2160p", "1080p", "720p", "320 kbps"
  fps?: number;
  filesizeBytes?: number;
  ext: string; // e.g. "mp4", "webm", "mp3", "m4a", "jpg", "png", "zip", "srt", "vtt"
  directUrl: string;
  headers?: Record<string, string>;
  isCleanNoWatermark?: boolean;
  isVideo?: boolean;
  isAudio?: boolean;
  isImage?: boolean;
  isSubtitle?: boolean;
  isAlbumPack?: boolean;
  allAlbumUrls?: string[];
  badge?: string; // e.g. "8K ULTRA", "4K UHD", "NO WATERMARK", "320 KBPS", "SUBTITLE"
  customTitle?: string;
  customFilename?: string;
  thumbnailUrl?: string;
  durationSec?: number;
  itag?: number;
  codec?: string;
  protocol?: string;
  container?: string;
  isDownloadable?: boolean;
  isStreamable?: boolean;
  downloadOnly?: boolean;
  /** Provenance and transport validation supplied by the native public crawler. */
  verification?: MediaVerification;
}

export type MediaVerificationStatus = 'verified' | 'wrapper' | 'blocked' | 'session-bound' | 'unverified';

export interface MediaVerification {
  status: MediaVerificationStatus;
  sourceUrl?: string;
  parentUrl?: string;
  redirectChain?: string[];
  mimeType?: string;
  contentLength?: number;
  validation?: string;
  reason?: string;
  rangeSupported?: boolean;
}

/** Opaque, safe-to-round-trip crawler state. It never includes cookies or credentials. */
export interface RemoteDiscoveryState {
  cursor?: unknown;
  complete: boolean;
  pendingCount: number;
  inspectedPages: number;
  warnings?: string[];
  blockerReason?: string;
}

export interface ResolvedMediaItem {
  id: string;
  title: string;
  thumbnailUrl?: string;
  durationSec?: number;
  kind?: 'video' | 'image' | 'profile' | 'story' | 'audio' | 'doc' | 'zip' | 'other' | 'unsupported';
  selectedFormatId?: string;
  formats: StreamQualityFormat[];
}

export interface ResolveOptions {
  passcode?: string;
  /** Continue a bounded public discovery session from a previous result. */
  discoveryCursor?: unknown;
}

export type ResolutionStage = 'analyze' | 'resolve' | 'discover' | 'validate' | 'ready';

export interface ResolutionTrace {
  resolverName: string;
  sourceUrl: string;
  finalUrl: string;
  inspectedPages?: number;
  candidateCount: number;
  securityStatus: 'validated' | 'provider' | 'fallback';
  stages: ResolutionStage[];
}

export interface ResolvedMediaInfo {
  url: string;
  platform: PlatformKind;
  platformName: string;
  title: string;
  author?: string;
  authorAvatar?: string;
  durationSec?: number;
  thumbnailUrl?: string;
  albumImages?: string[];
  description?: string;
  formats: StreamQualityFormat[];
  selectedFormatId: string;
  mediaItems?: ResolvedMediaItem[];
  rawStreams?: RawStreamItem[];
  subtitles?: SubtitleTrackItem[];
  chapters?: Array<{ title: string; startSec: number; endSec?: number; thumbnailUrl?: string }>;
  isPlaylist?: boolean;
  playlistId?: string;
  artist?: string;
  isDirectFile?: boolean;
  requiresHeaders?: boolean;
  customHeaders?: Record<string, string>;
  requiresPassword?: boolean;
  passwordError?: boolean;
  totalItems?: number;
  discovery?: RemoteDiscoveryState;
  resolutionTrace?: ResolutionTrace;
  resolvedAt: number;
}

export interface LinkResolverProvider {
  readonly name: string;
  readonly platform: PlatformKind;
  canHandle(url: string): boolean;
  resolve(url: string, signal?: AbortSignal, options?: ResolveOptions): Promise<ResolvedMediaInfo | null>;
}
